-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 01:29:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sneakers-house
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sneakers-house
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sneakers-house` DEFAULT CHARACTER SET utf8 ;
USE `sneakers-house` ;

-- -----------------------------------------------------
-- Table `sneakers-house`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sneakers-house`.`usuario` ;

CREATE TABLE IF NOT EXISTS `sneakers-house`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `pwd` VARCHAR(100) NULL,
  `cpf` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `endereco` VARCHAR(100) NULL,
  `numero` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sneakers-house`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sneakers-house`.`pedido` ;

CREATE TABLE IF NOT EXISTS `sneakers-house`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `total` DECIMAL(10,2) NULL,
  `entrega` DATE NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sneakers-house`.`produto_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sneakers-house`.`produto_categoria` ;

CREATE TABLE IF NOT EXISTS `sneakers-house`.`produto_categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sneakers-house`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sneakers-house`.`produto` ;

CREATE TABLE IF NOT EXISTS `sneakers-house`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NULL,
  `imagemDestaque` VARCHAR(100) NULL,
  `imagens` VARCHAR(150) NULL,
  `cores` VARCHAR(45) NULL,
  `valor` DECIMAL(10,2) NULL,
  `desconto` INT NULL,
  `descricao` VARCHAR(1000) NULL,
  `tamanhos` INT NULL,
  `destaque` TINYINT NULL,
  `oferta` TINYINT NULL,
  `fk_id_produto_categoria` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sneakers-house`.`pedido_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sneakers-house`.`pedido_item` ;

CREATE TABLE IF NOT EXISTS `sneakers-house`.`pedido_item` (
  `id_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id_pedido`, `id_produto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
