INSERT INTO `sneakers-house`.`produto`
(`id`,
`sku`,
`marca`,
`nome`,
`imagemDestaque`,
`imagens`,
`cores`,
`valor`,
`desconto`,
`descricao`,
`tamanhos`,
`destaque`,
`oferta`,
`id_produto_categoria`)
VALUES
(3,
'DR0156300',
'Nike',
'Nike Dunk Low Safari Swoosh',
'nike-dunk-low-safari-01.png',
'nike-dunk-low-safari-02.png',
'verde',
599.90,
299.90,
'Criado para as quadras, mas conquistou as ruas, o ícone do basquete dos anos 80 retorna com detalhes clássicos e um toque retrô. As sobreposições de camurça flexível ajudam o estilo vintage do Dunk Low, enquanto os logotipos Swoosh estampados em negrito adicionam um toque selvagem. Além disso, o colarinho acolchoado de baixo perfil mantém você confortável em qualquer lugar.',
'37',
1,
0,
2),

(4,
'DR0156300',
'Nike',
'Nike Dunk Low Safari Swoosh',
'nike-dunk-low-safari-01.png',
'nike-dunk-low-safari-02.png',
'verde',
599.90,
299.90,
'Criado para as quadras, mas conquistou as ruas, o ícone do basquete dos anos 80 retorna com detalhes clássicos e um toque retrô. As sobreposições de camurça flexível ajudam o estilo vintage do Dunk Low, enquanto os logotipos Swoosh estampados em negrito adicionam um toque selvagem. Além disso, o colarinho acolchoado de baixo perfil mantém você confortável em qualquer lugar.',
'37',
1,
0,
2)
